name: Plan Infrastructure
on:
  pull_request:
    branches:
      - main

jobs:
  plan:
    name: Plan Terraform
    #env:
    #  TF_VAR_allowed_account_id: ${{ secrets.ALLOWED_ACCOUNT_ID }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: open
      - run: echo "Your PR is ${PR}"
        if: success() && steps.findPr.outputs.number
        env:
          PR: ${{ steps.findPr.outputs.pr }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Init
        run: |
          cd infrastructure/aws
          terraform init -backend-config="key=terraform_pr$PR.tf.state"

      - name: Terraform Plan
        run: |
          cd infrastructure/aws
          echo "KEY=VALUE" >>$GITHUB_OUTPUT
          terraform plan


# SEE https://blog.testdouble.com/posts/2021-12-07-elevate-your-terraform-workflow-with-github-actions/
# https://nedinthecloud.com/2021/12/08/github-actions-with-terraform/